#define FSCRYPTDISK_MAJOR_VERSION 2
#define FSCRYPTDISK_MINOR_VERSION 1
#define FSCRYPTDISK_MINOR_LOW_VERSION 2

#define STR_EXPAND(tok) #tok
#define STR(tok) STR_EXPAND(tok)

#define FSCRYPTDISK_RC_VERSION_FLD FSCRYPTDISK_MAJOR_VERSION, FSCRYPTDISK_MINOR_VERSION, FSCRYPTDISK_MINOR_LOW_VERSION
#define FSCRYPTDISK_RC_VERSION_STR STR(FSCRYPTDISK_MAJOR_VERSION) "." STR(FSCRYPTDISK_MINOR_VERSION) "." STR(FSCRYPTDISK_MINOR_LOW_VERSION)
